"""Export a shareable markdown report."""

from __future__ import annotations

from datetime import datetime, timezone

from utils.gap_analysis import GapAnalysis
from utils.personas import Persona
from utils.rewriter import RewritePack


def build_markdown_report(
    persona: Persona,
    analysis: GapAnalysis | None,
    rewrites: RewritePack | None,
) -> str:
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Building THE IT GUY — Career Engine Report",
        "",
        f"- Persona: **{persona.label}**",
        f"- Generated: {stamp}",
        "",
    ]
    if analysis:
        lines.extend(
            [
                f"## Match score: {analysis.match_score}%",
                "",
                analysis.summary,
                "",
                "### Score breakdown",
            ]
        )
        for key, value in analysis.breakdown.items():
            lines.append(f"- {key.replace('_', ' ').title()}: {value}%")
        if analysis.matched_skills:
            lines.extend(["", "### Matched skills", *[f"- {item}" for item in analysis.matched_skills]])
        if analysis.missing_hard_skills:
            lines.extend(["", "### Missing hard skills"])
            for item in analysis.missing_hard_skills:
                lines.append(f"- **{item.name}** — {item.why} Next: {item.next_step}")
        if analysis.missing_enterprise_terms:
            lines.extend(["", "### Missing enterprise terminology"])
            for item in analysis.missing_enterprise_terms:
                lines.append(f"- **{item.name}** — {item.why} Phrase: {item.next_step}")
        if analysis.quick_wins:
            lines.extend(["", "### Quick wins", *[f"- {item}" for item in analysis.quick_wins]])
        if analysis.interview_questions:
            lines.extend(["", "### Likely interview questions", *[f"- {item}" for item in analysis.interview_questions]])
        plan = analysis.plan_30_60_90
        if any(plan.get(key) for key in ("30_days", "60_days", "90_days")):
            lines.extend(["", "### 30 / 60 / 90 plan"])
            for key, title in (("30_days", "30 days"), ("60_days", "60 days"), ("90_days", "90 days")):
                if plan.get(key):
                    lines.append(f"**{title}**")
                    lines.extend(f"- {item}" for item in plan[key])
        if analysis.warning:
            lines.extend(["", f"> Fallback note: {analysis.warning}"])

    if rewrites and rewrites.items:
        lines.extend(["", "## Rewritten bullets"])
        for item in rewrites.items:
            lines.extend(
                [
                    "",
                    f"**Before:** {item.original}",
                    "",
                    f"**After:** {item.rewritten}",
                    "",
                    f"*{item.why_stronger}*",
                ]
            )
        if rewrites.warning:
            lines.extend(["", f"> Fallback note: {rewrites.warning}"])

    lines.extend(["", "---", "_Generated by Building THE IT GUY: Career Engine. Do not invent evidence._", ""])
    return "\n".join(lines)
